module.exports = [
  {
    id: 101,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian+1.jpg'],
    foodType: 'Italian',
    name: ['Josh Alamillo', 'Nicholas Peyrichou', 'Mat Bagnall'],
    comment: ['I have never had a bad experience when I am here', 'This is my go-to resturant', 'We come here 5 times a week it is so good'],
  },
  {
    id: 102,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french10.jpg'],
    foodType: 'French',
    name: ['Beth Johnson', 'Javier Enriquez', 'Mat Bagnall'],
    comment: ['I have never had a bad experience when I am here', 'I love the food and service', 'This is my go-to resturant'],
  },
  {
    id: 103,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg'],
    foodType: 'Brunch',
    name: ['Airyque Ervin', 'Philip Lee', 'Mark Kuba'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 104,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: ['Michael Ngo', 'Josh Glandorf', 'Josh Glandorf'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'This is my go-to resturant'],
  },
  {
    id: 105,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: ['Nicholas Peyrichou', 'Josh Alamillo', 'Philip Lee'],
    comment: ['So much food and soooo good', 'So much food and soooo good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 106,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese2.jpg'],
    foodType: 'Chinese',
    name: ['Josh Alamillo', 'Angel Hernandez', 'Mark Kuba'],
    comment: ['So much food and soooo good', 'I have never had a bad experience when I am here', 'I have never had a bad experience when I am here'],
  },
  {
    id: 107,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg'],
    foodType: 'Mexican',
    name: ['Airyque Ervin', 'Shaital Desai', 'Josh Alamillo'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'So much food and soooo good'],
  },
  {
    id: 108,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg'],
    foodType: 'American',
    name: ['Josh Glandorf', 'Josh Alamillo', 'Josh Alamillo'],
    comment: ['So much food and soooo good', 'We come here 5 times a week it is so good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 109,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg'],
    foodType: 'Mexican',
    name: ['Javier Enriquez', 'Wayman Ng', 'Mat Bagnall'],
    comment: ['We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 110,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: ['Josh Glandorf', 'Arjun Chemparathy', 'Josh Glandorf'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'So much food and soooo good'],
  },
  {
    id: 111,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg'],
    foodType: 'Indian',
    name: ['Namson Leung', 'Arjun Chemparathy', 'Beth Johnson'],
    comment: ['I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 112,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian5.jpg'],
    foodType: 'Indian',
    name: ['Wayman Ng', 'Mat Bagnall', 'Makan Azarshahy'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good', 'This is my go-to resturant'],
  },
  {
    id: 113,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg'],
    foodType: 'Chinese',
    name: ['Arjun Chemparathy', 'Josh Alamillo', 'Arjun Chemparathy'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'I have never had a bad experience when I am here'],
  },
  {
    id: 114,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: ['Nicholas Peyrichou', 'Mat Bagnall', 'Arjun Chemparathy'],
    comment: ['So much food and soooo good', 'So much food and soooo good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 115,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg'],
    foodType: 'American',
    name: ['Andy Nguyen', 'Javier Enriquez', 'Makan Azarshahy'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have never had a bad experience when I am here', 'I have never had a bad experience when I am here'],
  },
  {
    id: 116,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: ['Philip Lee', 'Mat Bagnall', 'Michael Ngo'],
    comment: ['I have never had a bad experience when I am here', 'I have never had a bad experience when I am here', 'This is my go-to resturant'],
  },
  {
    id: 117,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg'],
    foodType: 'Brunch',
    name: ['Nicholas Peyrichou', 'Namson Leung', 'Beth Johnson'],
    comment: ['I love the food and service', 'I have never had a bad experience when I am here', 'So much food and soooo good'],
  },
  {
    id: 118,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: ['Namson Leung', 'Makan Azarshahy', 'Philip Lee'],
    comment: ['I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 119,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg'],
    foodType: 'American',
    name: ['Namson Leung', 'Andy Nguyen', 'Beth Johnson'],
    comment: ['I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 120,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg'],
    foodType: 'Italian',
    name: ['Josh Glandorf', 'Philip Lee', 'Angel Hernandez'],
    comment: ['I love the food and service', 'We come here 5 times a week it is so good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 121,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg'],
    foodType: 'Pizza',
    name: ['Namson Leung', 'Wayman Ng', 'Airyque Ervin'],
    comment: ['This is my go-to resturant', 'I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 122,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese2.jpg'],
    foodType: 'Chinese',
    name: ['Javier Enriquez', 'Airyque Ervin', 'Makan Azarshahy'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'This is my go-to resturant'],
  },
  {
    id: 123,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg'],
    foodType: 'Chinese',
    name: ['Arjun Chemparathy', 'Josh Glandorf', 'Shaital Desai'],
    comment: ['I love the food and service', 'I love the food and service', 'So much food and soooo good'],
  },
  {
    id: 124,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg'],
    foodType: 'Mexican',
    name: ['Airyque Ervin', 'Mark Kuba', 'Andy Nguyen'],
    comment: ['This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good'],
  },
  {
    id: 125,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg'],
    foodType: 'French',
    name: ['Josh Alamillo', 'Andy Nguyen', 'Nicholas Peyrichou'],
    comment: ['I have never had a bad experience when I am here', 'We come here 5 times a week it is so good', 'I love the food and service'],
  },
  {
    id: 126,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg'],
    foodType: 'Brunch',
    name: ['Namson Leung', 'Wayman Ng', 'Makan Azarshahy'],
    comment: ['I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family', 'This is my go-to resturant'],
  },
  {
    id: 127,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american19.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg'],
    foodType: 'American',
    name: ['Arjun Chemparathy', 'Josh Glandorf', 'Namson Leung'],
    comment: ['We come here 5 times a week it is so good', 'I have never had a bad experience when I am here', 'I have never had a bad experience when I am here'],
  },
  {
    id: 128,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg'],
    foodType: 'Brunch',
    name: ['Airyque Ervin', 'Mark Kuba', 'Josh Glandorf'],
    comment: ['We come here 5 times a week it is so good', 'This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 129,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg'],
    foodType: 'Pizza',
    name: ['Namson Leung', 'Mat Bagnall', 'Makan Azarshahy'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'I love the food and service'],
  },
  {
    id: 130,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg'],
    foodType: 'American',
    name: ['Josh Alamillo', 'Josh Alamillo', 'Airyque Ervin'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'This is my go-to resturant'],
  },
  {
    id: 131,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: ['Shaital Desai', 'Mat Bagnall', 'Mat Bagnall'],
    comment: ['So much food and soooo good', 'I love the food and service', 'I have never had a bad experience when I am here'],
  },
  {
    id: 132,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg'],
    foodType: 'Mexican',
    name: ['Mark Kuba', 'Nicholas Peyrichou', 'Airyque Ervin'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'We come here 5 times a week it is so good'],
  },
  {
    id: 133,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: ['Wayman Ng', 'Mat Bagnall', 'Shaital Desai'],
    comment: ['I have never had a bad experience when I am here', 'I love the food and service', 'I love the food and service'],
  },
  {
    id: 134,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: ['Mark Kuba', 'Namson Leung', 'Philip Lee'],
    comment: ['This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 135,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg'],
    foodType: 'Pizza',
    name: ['Philip Lee', 'Josh Glandorf', 'Shaital Desai'],
    comment: ['We come here 5 times a week it is so good', 'I love the food and service', 'We come here 5 times a week it is so good'],
  },
  {
    id: 136,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg'],
    foodType: 'Indian',
    name: ['Shaital Desai', 'Namson Leung', 'Makan Azarshahy'],
    comment: ['We come here 5 times a week it is so good', 'I love the food and service', 'I have never had a bad experience when I am here'],
  },
  {
    id: 137,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg'],
    foodType: 'Indian',
    name: ['Wayman Ng', 'Michael Ngo', 'Angel Hernandez'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'This is my go-to resturant', 'This is my go-to resturant'],
  },
  {
    id: 138,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg'],
    foodType: 'Chinese',
    name: ['Mark Kuba', 'Wayman Ng', 'Arjun Chemparathy'],
    comment: ['I have never had a bad experience when I am here', 'So much food and soooo good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 139,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: ['Shaital Desai', 'Javier Enriquez', 'Beth Johnson'],
    comment: ['We come here 5 times a week it is so good', 'So much food and soooo good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 140,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: ['Josh Alamillo', 'Wayman Ng', 'Philip Lee'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'I have never had a bad experience when I am here'],
  },
  {
    id: 141,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: ['Nicholas Peyrichou', 'Mat Bagnall', 'Andy Nguyen'],
    comment: ['We come here 5 times a week it is so good', 'So much food and soooo good', 'I love the food and service'],
  },
  {
    id: 142,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch5.jpg'],
    foodType: 'Brunch',
    name: ['Wayman Ng', 'Arjun Chemparathy', 'Josh Alamillo'],
    comment: ['I love the food and service', 'I have never had a bad experience when I am here', 'We come here 5 times a week it is so good'],
  },
  {
    id: 143,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: ['Beth Johnson', 'Andy Nguyen', 'Mark Kuba'],
    comment: ['I have never had a bad experience when I am here', 'I love the food and service', 'So much food and soooo good'],
  },
  {
    id: 144,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: ['Namson Leung', 'Angel Hernandez', 'Namson Leung'],
    comment: ['I have never had a bad experience when I am here', 'We come here 5 times a week it is so good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 145,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg'],
    foodType: 'Italian',
    name: ['Beth Johnson', 'Namson Leung', 'Beth Johnson'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 146,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza11.jpg'],
    foodType: 'Pizza',
    name: ['Josh Glandorf', 'Josh Alamillo', 'Mark Kuba'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'I love the food and service'],
  },
  {
    id: 147,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese8.jpg'],
    foodType: 'Chinese',
    name: ['Angel Hernandez', 'Nicholas Peyrichou', 'Arjun Chemparathy'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have never had a bad experience when I am here', 'I have never had a bad experience when I am here'],
  },
  {
    id: 148,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: ['Michael Ngo', 'Javier Enriquez', 'Nicholas Peyrichou'],
    comment: ['We come here 5 times a week it is so good', 'I love the food and service', 'This is my go-to resturant'],
  },
  {
    id: 149,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg'],
    foodType: 'Mexican',
    name: ['Shaital Desai', 'Nicholas Peyrichou', 'Beth Johnson'],
    comment: ['I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 150,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: ['Javier Enriquez', 'Shaital Desai', 'Angel Hernandez'],
    comment: ['So much food and soooo good', 'I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 151,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg'],
    foodType: 'Italian',
    name: ['Andy Nguyen', 'Angel Hernandez', 'Josh Glandorf'],
    comment: ['I have never had a bad experience when I am here', 'So much food and soooo good', 'This is my go-to resturant'],
  },
  {
    id: 152,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: ['Philip Lee', 'Josh Alamillo', 'Josh Glandorf'],
    comment: ['I have never had a bad experience when I am here', 'This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 153,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican19.jpg'],
    foodType: 'Mexican',
    name: ['Mat Bagnall', 'Philip Lee', 'Mark Kuba'],
    comment: ['This is my go-to resturant', 'So much food and soooo good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 154,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian+1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg'],
    foodType: 'Italian',
    name: ['Michael Ngo', 'Namson Leung', 'Shaital Desai'],
    comment: ['This is my go-to resturant', 'So much food and soooo good', 'This is my go-to resturant'],
  },
  {
    id: 155,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg'],
    foodType: 'Mexican',
    name: ['Airyque Ervin', 'Makan Azarshahy', 'Mat Bagnall'],
    comment: ['This is my go-to resturant', 'So much food and soooo good', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 156,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican19.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican8.jpg'],
    foodType: 'Mexican',
    name: ['Josh Alamillo', 'Airyque Ervin', 'Nicholas Peyrichou'],
    comment: ['I love the food and service', 'I have never had a bad experience when I am here', 'We come here 5 times a week it is so good'],
  },
  {
    id: 157,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg'],
    foodType: 'Mexican',
    name: ['Michael Ngo', 'Mat Bagnall', 'Airyque Ervin'],
    comment: ['So much food and soooo good', 'I have never had a bad experience when I am here', 'I love the food and service'],
  },
  {
    id: 158,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg'],
    foodType: 'American',
    name: ['Mark Kuba', 'Nicholas Peyrichou', 'Andy Nguyen'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I love the food and service', 'I have never had a bad experience when I am here'],
  },
  {
    id: 159,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg'],
    foodType: 'Mexican',
    name: ['Philip Lee', 'Airyque Ervin', 'Mat Bagnall'],
    comment: ['I love the food and service', 'We come here 5 times a week it is so good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 160,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg'],
    foodType: 'Italian',
    name: ['Josh Alamillo', 'Mark Kuba', 'Namson Leung'],
    comment: ['I love the food and service', 'So much food and soooo good', 'This is my go-to resturant'],
  },
  {
    id: 161,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg'],
    foodType: 'Mexican',
    name: ['Namson Leung', 'Shaital Desai', 'Mark Kuba'],
    comment: ['We come here 5 times a week it is so good', 'I love the food and service', 'I have never had a bad experience when I am here'],
  },
  {
    id: 162,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican14.jpg'],
    foodType: 'Mexican',
    name: ['Nicholas Peyrichou', 'Nicholas Peyrichou', 'Airyque Ervin'],
    comment: ['I have never had a bad experience when I am here', 'I love the food and service', 'I have never had a bad experience when I am here'],
  },
  {
    id: 163,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: ['Namson Leung', 'Angel Hernandez', 'Airyque Ervin'],
    comment: ['So much food and soooo good', 'This is my go-to resturant', 'I love the food and service'],
  },
  {
    id: 164,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg'],
    foodType: 'Mexican',
    name: ['Andy Nguyen', 'Nicholas Peyrichou', 'Josh Glandorf'],
    comment: ['We come here 5 times a week it is so good', 'I love the food and service', 'I love the food and service'],
  },
  {
    id: 165,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg'],
    foodType: 'American',
    name: ['Angel Hernandez', 'Namson Leung', 'Makan Azarshahy'],
    comment: ['This is my go-to resturant', 'I love the food and service', 'We come here 5 times a week it is so good'],
  },
  {
    id: 166,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: ['Philip Lee', 'Josh Glandorf', 'Namson Leung'],
    comment: ['We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good'],
  },
  {
    id: 167,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: ['Beth Johnson', 'Philip Lee', 'Beth Johnson'],
    comment: ['We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 168,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg'],
    foodType: 'Pizza',
    name: ['Beth Johnson', 'Nicholas Peyrichou', 'Mat Bagnall'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family', 'This is my go-to resturant'],
  },
  {
    id: 169,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg'],
    foodType: 'American',
    name: ['Namson Leung', 'Mark Kuba', 'Namson Leung'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 170,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg'],
    foodType: 'American',
    name: ['Wayman Ng', 'Angel Hernandez', 'Mark Kuba'],
    comment: ['We come here 5 times a week it is so good', 'I have never had a bad experience when I am here', 'We come here 5 times a week it is so good'],
  },
  {
    id: 171,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg'],
    foodType: 'Brunch',
    name: ['Javier Enriquez', 'Mat Bagnall', 'Javier Enriquez'],
    comment: ['I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family', 'This is my go-to resturant'],
  },
  {
    id: 172,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: ['Philip Lee', 'Angel Hernandez', 'Josh Alamillo'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have never had a bad experience when I am here', 'This is my go-to resturant'],
  },
  {
    id: 173,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg'],
    foodType: 'Brunch',
    name: ['Shaital Desai', 'Mark Kuba', 'Josh Alamillo'],
    comment: ['This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family', 'I love the food and service'],
  },
  {
    id: 174,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch8.jpg'],
    foodType: 'Brunch',
    name: ['Arjun Chemparathy', 'Angel Hernandez', 'Javier Enriquez'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good', 'So much food and soooo good'],
  },
  {
    id: 175,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg'],
    foodType: 'Brunch',
    name: ['Mark Kuba', 'Makan Azarshahy', 'Mat Bagnall'],
    comment: ['I love the food and service', 'This is my go-to resturant', 'I have never had a bad experience when I am here'],
  },
  {
    id: 176,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg'],
    foodType: 'Pizza',
    name: ['Mark Kuba', 'Mark Kuba', 'Philip Lee'],
    comment: ['We come here 5 times a week it is so good', 'This is my go-to resturant', 'This is my go-to resturant'],
  },
  {
    id: 177,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg'],
    foodType: 'Italian',
    name: ['Nicholas Peyrichou', 'Javier Enriquez', 'Namson Leung'],
    comment: ['So much food and soooo good', 'I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 178,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american19.jpg'],
    foodType: 'American',
    name: ['Airyque Ervin', 'Mark Kuba', 'Mark Kuba'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 179,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg'],
    foodType: 'French',
    name: ['Michael Ngo', 'Wayman Ng', 'Beth Johnson'],
    comment: ['So much food and soooo good', 'I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 180,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: ['Andy Nguyen', 'Wayman Ng', 'Mat Bagnall'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 181,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg'],
    foodType: 'Chinese',
    name: ['Javier Enriquez', 'Angel Hernandez', 'Shaital Desai'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 182,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch4.jpg'],
    foodType: 'Brunch',
    name: ['Mark Kuba', 'Mark Kuba', 'Nicholas Peyrichou'],
    comment: ['I have never had a bad experience when I am here', 'This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 183,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg'],
    foodType: 'Indian',
    name: ['Mat Bagnall', 'Nicholas Peyrichou', 'Arjun Chemparathy'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 184,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg'],
    foodType: 'Brunch',
    name: ['Angel Hernandez', 'Nicholas Peyrichou', 'Michael Ngo'],
    comment: ['I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 185,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: ['Andy Nguyen', 'Angel Hernandez', 'Josh Alamillo'],
    comment: ['So much food and soooo good', 'We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 186,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza5.jpg'],
    foodType: 'Pizza',
    name: ['Nicholas Peyrichou', 'Angel Hernandez', 'Javier Enriquez'],
    comment: ['This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good'],
  },
  {
    id: 187,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: ['Andy Nguyen', 'Philip Lee', 'Makan Azarshahy'],
    comment: ['I love the food and service', 'So much food and soooo good', 'I have never had a bad experience when I am here'],
  },
  {
    id: 188,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg'],
    foodType: 'Mexican',
    name: ['Makan Azarshahy', 'Nicholas Peyrichou', 'Beth Johnson'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 189,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg'],
    foodType: 'Pizza',
    name: ['Makan Azarshahy', 'Michael Ngo', 'Beth Johnson'],
    comment: ['So much food and soooo good', 'I love the food and service', 'So much food and soooo good'],
  },
  {
    id: 190,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg'],
    foodType: 'Indian',
    name: ['Arjun Chemparathy', 'Michael Ngo', 'Philip Lee'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I love the food and service', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 191,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg'],
    foodType: 'Mexican',
    name: ['Javier Enriquez', 'Javier Enriquez', 'Michael Ngo'],
    comment: ['We come here 5 times a week it is so good', 'This is my go-to resturant', 'We come here 5 times a week it is so good'],
  },
  {
    id: 192,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: ['Nicholas Peyrichou', 'Josh Alamillo', 'Wayman Ng'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family', 'So much food and soooo good'],
  },
  {
    id: 193,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french9.jpg'],
    foodType: 'French',
    name: ['Arjun Chemparathy', 'Mat Bagnall', 'Andy Nguyen'],
    comment: ['We come here 5 times a week it is so good', 'We come here 5 times a week it is so good', 'We come here 5 times a week it is so good'],
  },
  {
    id: 194,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg'],
    foodType: 'Italian',
    name: ['Arjun Chemparathy', 'Andy Nguyen', 'Arjun Chemparathy'],
    comment: ['We come here 5 times a week it is so good', 'This is my go-to resturant', 'So much food and soooo good'],
  },
  {
    id: 195,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg'],
    foodType: 'American',
    name: ['Mark Kuba', 'Philip Lee', 'Angel Hernandez'],
    comment: ['So much food and soooo good', 'We come here 5 times a week it is so good', 'So much food and soooo good'],
  },
  {
    id: 196,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg'],
    foodType: 'American',
    name: ['Angel Hernandez', 'Airyque Ervin', 'Arjun Chemparathy'],
    comment: ['I love the food and service', 'I have never had a bad experience when I am here', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 197,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg'],
    foodType: 'Indian',
    name: ['Mark Kuba', 'Shaital Desai', 'Makan Azarshahy'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'We come here 5 times a week it is so good', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 198,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: ['Philip Lee', 'Josh Alamillo', 'Javier Enriquez'],
    comment: ['So much food and soooo good', 'I love the food and service', 'We come here 5 times a week it is so good'],
  },
  {
    id: 199,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: ['Beth Johnson', 'Andy Nguyen', 'Josh Alamillo'],
    comment: ['This is my go-to resturant', 'I have been going here for years and it is a great place to hang out with friends and family', 'I have been going here for years and it is a great place to hang out with friends and family'],
  },
  {
    id: 200,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican14.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg'],
    foodType: 'Mexican',
    name: ['Michael Ngo', 'Josh Alamillo', 'Mark Kuba'],
    comment: ['I have been going here for years and it is a great place to hang out with friends and family', 'I love the food and service', 'I love the food and service'],
  },
];
