module.exports = [
  {
    id: 101,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian+1.jpg'],
    foodType: 'Italian',
    name: 'Airyque Ervin',
    comment: 'Wow food was so good',
  },
  {
    id: 102,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french10.jpg'],
    foodType: 'French',
    name: 'Javier Enriquez',
    comment: 'Good food and quick service',
  },
  {
    id: 103,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg'],
    foodType: 'Brunch',
    name: 'Wayman Ng',
    comment: 'I have been going here for years and it is a great place to hang out with friends and family',
  },
  {
    id: 104,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: 'Andy Nguyen',
    comment: 'This is my go-to resturant',
  },
  {
    id: 105,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: 'Shaital Desai',
    comment: 'Just look at this food',
  },
  {
    id: 106,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese2.jpg'],
    foodType: 'Chinese',
    name: 'Beth Johnson',
    comment: 'I love the food and service',
  },
  {
    id: 107,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg'],
    foodType: 'Mexican',
    name: 'Beth Johnson',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 108,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg'],
    foodType: 'American',
    name: 'Mat Bagnall',
    comment: 'Wow food was so good',
  },
  {
    id: 109,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg'],
    foodType: 'Mexican',
    name: 'Wayman Ng',
    comment: 'I rate this food 11 out of 10',
  },
  {
    id: 110,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: 'Josh Glandorf',
    comment: 'If you like good food you\'ll like it here',
  },
  {
    id: 111,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg'],
    foodType: 'Indian',
    name: 'Michael Ngo',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 112,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian5.jpg'],
    foodType: 'Indian',
    name: 'Mat Bagnall',
    comment: 'So much food and soooo good',
  },
  {
    id: 113,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg'],
    foodType: 'Chinese',
    name: 'Javier Enriquez',
    comment: 'So much food and soooo good',
  },
  {
    id: 114,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: 'Mark Kuba',
    comment: 'Best around highly recommend',
  },
  {
    id: 115,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg'],
    foodType: 'American',
    name: 'Namson Leung',
    comment: 'If you like good food you\'ll like it here',
  },
  {
    id: 116,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: 'Javier Enriquez',
    comment: 'I have been going here for years and it is a great place to hang out with friends and family',
  },
  {
    id: 117,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg'],
    foodType: 'Brunch',
    name: 'Wayman Ng',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 118,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: 'Arjun Chemparathy',
    comment: 'The food is to die for',
  },
  {
    id: 119,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american2.jpg'],
    foodType: 'American',
    name: 'Mark Kuba',
    comment: 'I love the food and service',
  },
  {
    id: 120,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg'],
    foodType: 'Italian',
    name: 'Arjun Chemparathy',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 121,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg'],
    foodType: 'Pizza',
    name: 'Javier Enriquez',
    comment: 'Best around highly recommend',
  },
  {
    id: 122,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese2.jpg'],
    foodType: 'Chinese',
    name: 'Airyque Ervin',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 123,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg'],
    foodType: 'Chinese',
    name: 'Angel Hernandez',
    comment: 'If you like good food you\'ll like it here',
  },
  {
    id: 124,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg'],
    foodType: 'Mexican',
    name: 'Airyque Ervin',
    comment: 'This is my go-to resturant',
  },
  {
    id: 125,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg'],
    foodType: 'French',
    name: 'Josh Alamillo',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 126,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg'],
    foodType: 'Brunch',
    name: 'Andy Nguyen',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 127,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american19.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg'],
    foodType: 'American',
    name: 'Josh Alamillo',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 128,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg'],
    foodType: 'Brunch',
    name: 'Josh Glandorf',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 129,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg'],
    foodType: 'Pizza',
    name: 'Philip Lee',
    comment: 'Just look at this food',
  },
  {
    id: 130,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg'],
    foodType: 'American',
    name: 'Andy Nguyen',
    comment: 'Just look at this food',
  },
  {
    id: 131,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: 'Angel Hernandez',
    comment: 'I have never had a bad experience when I am here',
  },
  {
    id: 132,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg'],
    foodType: 'Mexican',
    name: 'Arjun Chemparathy',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 133,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg'],
    foodType: 'American',
    name: 'Nicholas Peyrichou',
    comment: 'The food is to die for',
  },
  {
    id: 134,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: 'Beth Johnson',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 135,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg'],
    foodType: 'Pizza',
    name: 'Philip Lee',
    comment: 'Good food and quick service',
  },
  {
    id: 136,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg'],
    foodType: 'Indian',
    name: 'Josh Glandorf',
    comment: 'Wow food was so good',
  },
  {
    id: 137,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg'],
    foodType: 'Indian',
    name: 'Arjun Chemparathy',
    comment: 'Wow food was so good',
  },
  {
    id: 138,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese7.jpg'],
    foodType: 'Chinese',
    name: 'Shaital Desai',
    comment: 'I rate this food 11 out of 10',
  },
  {
    id: 139,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: 'Namson Leung',
    comment: 'I have been going here for years and it is a great place to hang out with friends and family',
  },
  {
    id: 140,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: 'Javier Enriquez',
    comment: 'I love this place',
  },
  {
    id: 141,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: 'Angel Hernandez',
    comment: 'Best around highly recommend',
  },
  {
    id: 142,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch5.jpg'],
    foodType: 'Brunch',
    name: 'Michael Ngo',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 143,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg'],
    foodType: 'French',
    name: 'Mat Bagnall',
    comment: 'If you like good food you\'ll like it here',
  },
  {
    id: 144,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: 'Beth Johnson',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 145,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg'],
    foodType: 'Italian',
    name: 'Namson Leung',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 146,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza11.jpg'],
    foodType: 'Pizza',
    name: 'Nicholas Peyrichou',
    comment: 'Best around highly recommend',
  },
  {
    id: 147,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese8.jpg'],
    foodType: 'Chinese',
    name: 'Airyque Ervin',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 148,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese10.jpg'],
    foodType: 'Chinese',
    name: 'Shaital Desai',
    comment: 'I rate this food 11 out of 10',
  },
  {
    id: 149,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg'],
    foodType: 'Mexican',
    name: 'Michael Ngo',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 150,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: 'Makan Azarshahy',
    comment: 'Just look at this food',
  },
  {
    id: 151,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg'],
    foodType: 'Italian',
    name: 'Beth Johnson',
    comment: 'I rate this food 11 out of 10',
  },
  {
    id: 152,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: 'Angel Hernandez',
    comment: 'Wow food was so good',
  },
  {
    id: 153,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican19.jpg'],
    foodType: 'Mexican',
    name: 'Beth Johnson',
    comment: 'Good food and quick service',
  },
  {
    id: 154,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian+1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg'],
    foodType: 'Italian',
    name: 'Michael Ngo',
    comment: 'This is my go-to resturant',
  },
  {
    id: 155,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg'],
    foodType: 'Mexican',
    name: 'Mark Kuba',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 156,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican19.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican8.jpg'],
    foodType: 'Mexican',
    name: 'Airyque Ervin',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 157,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg'],
    foodType: 'Mexican',
    name: 'Wayman Ng',
    comment: 'Good food and quick service',
  },
  {
    id: 158,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg'],
    foodType: 'American',
    name: 'Andy Nguyen',
    comment: 'This is my go-to resturant',
  },
  {
    id: 159,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican17.jpg'],
    foodType: 'Mexican',
    name: 'Josh Glandorf',
    comment: 'Good food and quick service',
  },
  {
    id: 160,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg'],
    foodType: 'Italian',
    name: 'Wayman Ng',
    comment: 'Good food and quick service',
  },
  {
    id: 161,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican15.jpg'],
    foodType: 'Mexican',
    name: 'Josh Glandorf',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 162,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican14.jpg'],
    foodType: 'Mexican',
    name: 'Nicholas Peyrichou',
    comment: 'I rate this food 11 out of 10',
  },
  {
    id: 163,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: 'Airyque Ervin',
    comment: 'Good food and quick service',
  },
  {
    id: 164,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg'],
    foodType: 'Mexican',
    name: 'Mat Bagnall',
    comment: 'This is my go-to resturant',
  },
  {
    id: 165,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg'],
    foodType: 'American',
    name: 'Shaital Desai',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 166,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: 'Mat Bagnall',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 167,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: 'Namson Leung',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 168,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza2.jpg'],
    foodType: 'Pizza',
    name: 'Wayman Ng',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 169,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg'],
    foodType: 'American',
    name: 'Arjun Chemparathy',
    comment: 'I love this place',
  },
  {
    id: 170,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american21.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american5.jpg'],
    foodType: 'American',
    name: 'Mark Kuba',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 171,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg'],
    foodType: 'Brunch',
    name: 'Wayman Ng',
    comment: 'The food is to die for',
  },
  {
    id: 172,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: 'Josh Alamillo',
    comment: 'This is my go-to resturant',
  },
  {
    id: 173,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch11.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg'],
    foodType: 'Brunch',
    name: 'Airyque Ervin',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 174,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch8.jpg'],
    foodType: 'Brunch',
    name: 'Nicholas Peyrichou',
    comment: 'The food is to die for',
  },
  {
    id: 175,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg'],
    foodType: 'Brunch',
    name: 'Angel Hernandez',
    comment: 'had to share this amazing looking food',
  },
  {
    id: 176,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg'],
    foodType: 'Pizza',
    name: 'Philip Lee',
    comment: 'This is my go-to resturant',
  },
  {
    id: 177,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian8.jpg'],
    foodType: 'Italian',
    name: 'Mat Bagnall',
    comment: 'I highly recommend this place to everyone',
  },
  {
    id: 178,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american15.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american19.jpg'],
    foodType: 'American',
    name: 'Nicholas Peyrichou',
    comment: 'So much food and soooo good',
  },
  {
    id: 179,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french7.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg'],
    foodType: 'French',
    name: 'Javier Enriquez',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 180,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french5.jpg'],
    foodType: 'French',
    name: 'Josh Glandorf',
    comment: 'This is my go-to resturant',
  },
  {
    id: 181,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/chinese9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/chinese4.jpg'],
    foodType: 'Chinese',
    name: 'Philip Lee',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 182,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch4.jpg'],
    foodType: 'Brunch',
    name: 'Makan Azarshahy',
    comment: 'Good food and quick service',
  },
  {
    id: 183,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian4.jpg'],
    foodType: 'Indian',
    name: 'Shaital Desai',
    comment: 'Just look at this food',
  },
  {
    id: 184,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/brunch1.jpg'],
    foodType: 'Brunch',
    name: 'Javier Enriquez',
    comment: 'Wow food was so good',
  },
  {
    id: 185,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg'],
    foodType: 'American',
    name: 'Beth Johnson',
    comment: 'The food is to die for',
  },
  {
    id: 186,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza5.jpg'],
    foodType: 'Pizza',
    name: 'Namson Leung',
    comment: 'I have been going here for years and it is a great place to hang out with friends and family',
  },
  {
    id: 187,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american9.jpg'],
    foodType: 'American',
    name: 'Nicholas Peyrichou',
    comment: 'I love this place',
  },
  {
    id: 188,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican5.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican12.jpg'],
    foodType: 'Mexican',
    name: 'Josh Glandorf',
    comment: 'Just look at how good this food looks',
  },
  {
    id: 189,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza4.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg'],
    foodType: 'Pizza',
    name: 'Nicholas Peyrichou',
    comment: 'This is my go-to resturant',
  },
  {
    id: 190,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian6.jpg'],
    foodType: 'Indian',
    name: 'Beth Johnson',
    comment: 'Best around highly recommend',
  },
  {
    id: 191,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican3.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican11.jpg'],
    foodType: 'Mexican',
    name: 'Angel Hernandez',
    comment: 'Just look at this food',
  },
  {
    id: 192,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/pizza1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/pizza8.jpg'],
    foodType: 'Pizza',
    name: 'Nicholas Peyrichou',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 193,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/french8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/french9.jpg'],
    foodType: 'French',
    name: 'Mat Bagnall',
    comment: 'I love the food and service',
  },
  {
    id: 194,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian5.jpg'],
    foodType: 'Italian',
    name: 'Mat Bagnall',
    comment: 'I have been going here for years and it is a great place to hang out with friends and family',
  },
  {
    id: 195,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american17.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg'],
    foodType: 'American',
    name: 'Beth Johnson',
    comment: 'This is my go-to resturant',
  },
  {
    id: 196,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/american1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american8.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/american20.jpg'],
    foodType: 'American',
    name: 'Javier Enriquez',
    comment: 'I love the food and service',
  },
  {
    id: 197,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/indian2.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/indian7.jpg'],
    foodType: 'Indian',
    name: 'Beth Johnson',
    comment: 'I have never had a bad experience when I am here',
  },
  {
    id: 198,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/italian10.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian6.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/italian9.jpg'],
    foodType: 'Italian',
    name: 'Namson Leung',
    comment: 'We come here 5 times a week it is so good',
  },
  {
    id: 199,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican13.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican18.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican10.jpg'],
    foodType: 'Mexican',
    name: 'Namson Leung',
    comment: 'This is my go-to resturant',
  },
  {
    id: 200,
    pictures: ['https://s3-us-west-1.amazonaws.com/foodigo/mexican14.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican1.jpg', 'https://s3-us-west-1.amazonaws.com/foodigo/mexican16.jpg'],
    foodType: 'Mexican',
    name: 'Namson Leung',
    comment: 'So much food and soooo good',
  },
];
